language: java
jdk:
  - openjdk8

branches:
  only:
  - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build 시 자동으로 test 수행)
script:
  - "./gradlew clean build"

install:
  - nvm install v8.10.0
  - npm install -g firebase-tools


after_success:
  - ./gradlew jacocoTestReport coveralls
  - firebase deploy --token $FIREBASE_TOKEN
